import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  "~/.config/alacritty/rose-pine/rose-pine.toml"
  # "~/.config/alacritty/zenbones/duckbones.toml"
  # "~/.config/alacritty/tokyonight/tokyonight_night.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 0.95 # 0.87
blur = true
startup_mode = "SimpleFullscreen"

[window.padding]
x = 10
y = 10

[colors.primary]
background = "#0a0a0a"

