import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  "~/.config/alacritty/rose-pinerrose-pine-moon.toml"
  # "~/.config/alacritty/rose-pinerrose-pine.toml"
  # "~/.config/alacritty/roseprime.toml"
  # "~/.config/alacritty/zenbones/duckbones.toml"
  # "~/.config/alacritty/tokyonight/tokyonight_night.toml"
  # "~/.config/alacritty/kanagawa/kanagawa_dragon.toml"
]

[env]
TERM = "screen-256color"

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
# family = "Hack Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font"

[window]
opacity = 0.87
startup_mode = "SimpleFullscreen"

# [window.padding]
# x = 10
# y = 10

[colors.primary]
background = "#0a0a0a"
